config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :leads
  get 'points/assign'
  get 'points/destroy'
  get 'points/consult'
  get 'points/view'
  resources :matriculations
  resources :contents do
    resources :user_contents do
      member do
        put 'like' => 'user_contents#like'
        get 'fijar' => 'user_contents#pinup'
        get 'banear' => 'user_contents#ban'
      end
    end
    resources :tests do
      post 'corregir' => 'tests#corregir'
    end
    post 'points' => 'points#consult'
    get 'publicar' => 'contents#publish'
    get 'deshabilitar' => 'contents#disable'
  end

  resources :courses do
    resources :chapters do
      get 'publicar' => 'chapters#publish'
    end
    get 'publicar' => 'courses#publish'
  end

  devise_for :users
  root 'home#index'
  get 'mycourses', to: 'courses#mycourses'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :course
  belongs_to :chapter
  has_rich_text :richContent
  has_many :contents

  include AASM

  aasm do
    # Declaramos los estados
    state :in_draft, initial: true
    state :published, :disabled

    # Declaramos los eventos
    event :publish do
      transitions from: %i[in_draft disabled], to: :published
    end

    event :unpublish do
      transitions from: %i[published disabled], to: :in_draft
    end

    event :disable do
      transitions from: %i[published in_draft], to: :disabled
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :set_course_modified, only: %i[publish disable]
  before_action :set_course, except: %i[index new create publish disable]
  before_action :check_permissions, except: %i[index new]
  before_action :check_god, only: %i[index]

  # GET /contents or /contents.json
  def index
    # Sólo acceden los administradores
    @contents = Content.all
  end

  # GET contents/1/publicar
  def publish
    # Sólo pueden publicar los admin
    if @permissions >= 30
      @content = Content.find(params[:content_id])
      if @content.published?
        @content.unpublish!
        redirect_to course_chapters_path(@course), notice: 'Dejamos el contenido en borrador'
      else
        @content.publish!
        redirect_to course_chapters_path(@course), notice: 'Publicamos el contenido'
      end
    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto, chinwenwencha.'
    end
  end

  # GET contents/1/disable
  def disable
    # Sólo pueden deshabilitar los admin
    if @permissions >= 30
      # Setea el contenido
      @content = Content.find(params[:content_id])

      if @content.disabled?

        redirect_to course_chapters_path(@course), notice: 'El contenido ya estaba deshabilitado.'
      else
        @content.disable!
        redirect_to course_chapters_path(@course), notice: 'Deshabilitamos el contenido.'
      end
    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto, chinwenwencha.'
    end
  end

  # GET /contents/1 or /contents/1.json
  def show
    # Sólo acceden los alumnos

    if @permissions >= 10

      if @content.requirements.nil?
        # Puede ver (no hay requerimientos)
        @show = true

      else

        contenido_requerido = Content.find_by(id: @content.requirements)
        puntos_requeridos = contenido_requerido.minimumScore

        tests_hechos = Point.select(:score).where(user: current_user, content_id: @content.requirements) # en el id: @content.requirement

        puntos_disponibles = 0
        # sumar score de los test hechos
        tests_hechos.each do |t|
          puntos_disponibles = puntos_disponibles.to_i + t.score.to_i
        end

        if puntos_disponibles < puntos_requeridos
          # No puede ver (No alcanzan los puntos)
          @show = false
          @data = [puntos_disponibles: puntos_disponibles, puntos_requeridos: puntos_requeridos, requerimiento: contenido_requerido]
        else
          # Puede ver (no le alcanzan los puntos)
          @show = true

        end
      end

      cape = Content.find(params[:id])
      @chapter = Chapter.find(cape.chapter_id)

      # Se le pasa el usuario y contenido como parámetros y devuelve la suma de los puntos
      puntos = Point.select(:score).where(user: current_user, content: @content)
      @points = 0
      puntos.each do |p|
        @points += p.score.to_i
      end

    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto, chinwenwencha.'
    end
  end

  # GET /contents/new
  def new
    # Sólo acceden los tutores
    # if @permissions >= 20
    @content = Content.new
    # else
    # Redirigir
    #  redirect_to root_path, notice: "No tenés permiso para esto, chinwenwencha."
    # end
  end

  # GET /contents/1/edit
  def edit
    # Sólo acceden los tutores
    redirect_to root_path, notice: 'No tenés permiso para esto, chinwenwencha.' unless @permissions >= 20
  end

  # POST /contents or /contents.json
  def create
    # Sólo acceden los tutores
    # if @permissions >= 20

    # content_params["course_id"] = params[:content][:course]
    # content_params["chapter_id"] = params[:content][:chapter]
    @content = Content.new(content_params)

    @content.course_id = params[:content][:course]
    @content.chapter_id = params[:content][:chapter]

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: '¡Bien! Acabás de crear flor de contenido.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
    # else
    # Redirigir
    #      redirect_to root_path, notice: "No tenés permiso para esto, chinwenwencha."
    # end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    # Sólo acceden los tutores
    if @permissions >= 20
      respond_to do |format|
        if @content.update(content_params)
          format.html { redirect_to @content, notice: 'El contenido ya está como a vos te gusta...' }
          format.json { render :show, status: :ok, location: @content }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @content.errors, status: :unprocessable_entity }
        end
      end
    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto, chinwenwencha.'
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    # Sólo acceden los tutores
    if @permissions >= 20
      @content.destroy
      respond_to do |format|
        format.html do
          redirect_to contents_url, notice: 'Borraste un contenido. Bien hecho... no era digno de TransmediAcademy.'
        end
        format.json { head :no_content }
      end
    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto, chinwenwencha.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def content_params
    params.require(:content).permit(:course_id, :chapter_id, :name, :sequence, :typeOfContent, :richContent,
                                    :priority, :testId, :requirements, :minimumScore, :goals, :embed)
  end

  def set_course
    cap = Content.find(params[:id])
    @course = Course.find(cap.course_id)
  end

  def set_course_modified
    cap = Content.find(params[:content_id])
    @course = Course.find(cap.course_id)
  end

  def check_permissions
    matricula = Matriculation.find_by(user: current_user, course: @course)

    @permissions = if matricula.nil?
                     0
                   else
                     matricula.permissions
                   end
  end

  def check_god
    if current_user.permissions.nil?
      redirect_to root_path, notice: 'Pfff... Tomate el palo...'
    else
      redirect_to root_path, notice: 'Naaa. Estás re loco vo, amigo.' unless current_user.permissions >= 50
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.haml
= form_for @content do |f|
  - if @content.errors.any?
    #error_explanation
      %h2= "#{pluralize(@content.errors.count, "error")} prohibited this content from being saved:"
      %ul
        - @content.errors.full_messages.each do |message|
          %li= message
  .fondoGris.py-8.px-4
    .mx-auto.rounded-lg.bg-white.shadow-lg.p-5.text-gray-700.max-w-full	
      .h3.text-xl Curso:
      .field.mb-3.flex-mx-2
        = f.text_field :course,  :class => 'textBox'
      .h3.text-xl Capítulo:
      .field.mb-3.flex-mx-2
        = f.text_field :chapter,  :class => 'textBox'
      .h3.text-xl Título
      .field.mb-3.flex-mx-2
        = f.text_field :name,  :class => 'textBox'
      .h3.text-xl Orden dentro del capítulo
      .field.mb-3.flex-mx-2
        = f.number_field :sequence,  :class => 'textBox'
      .h3.text-xl Tipo de contenido
      .field.mb-3.flex-mx-2
        = f.number_field :typeOfContent,  :class => 'textBox'
      .h3.text-xl.my-8 Contenido
      .field.mb-3.flex-mx-2.bg-white
        = f.rich_text_area :richContent,  :class => 'w-full prose max-w-none prose-indigo leading-6 rounded-b-md shadow-sm border border-gray-300 p-5 bg-white overflow-y-auto'
      .h3.text-xl Prioridad
      .field.mb-3.flex-mx-2
        = f.number_field :priority,  :class => 'textBox'
      .h3.text-xl Cuestionario relacionado
      .field.mb-3.flex-mx-2
        = f.number_field :testId,  :class => 'textBox'
      .h3.text-xl Requerimientos previos
      .field.mb-3.flex-mx-2
        = f.number_field :requirements,  :class => 'textBox'
      .h3.text-xl Puntaje mínimo de aprobación
      .field.mb-3.flex-mx-2
        = f.number_field :minimumScore,  :class => 'textBox'
      .h3.text-xl Objetivos que permite alcanzar
      .field.mb-3.flex-mx-2
        = f.text_field :goals,  :class => 'textBox'
      .actions.py-6
        = f.submit 'Publicar', :class => "botonLargo"

app/views/contents/edit.html.haml
%h1 Editing content

= render 'form'

= link_to 'Show', @content
\|
= link_to 'Back', contents_path

app/views/contents/index.html.haml
%h1 Listing contents

%table
  %thead
    %tr
      %th Course
      %th Chapter
      %th Name
      %th Order
      %th Type
      %th Richcontent
      %th Priority
      %th Testid
      %th Requirements
      %th Minimumscore
      %th Goals
      %th
      %th
      %th

  %tbody
    - @contents.each do |content|
      %tr
        %td= content.course
        %td= content.chapter
        %td= content.name
        %td= content.sequence
        %td= content.typeOfContent
        %td= content.richContent
        %td= content.priority
        %td= content.testId
        %td= content.requirements
        %td= content.minimumScore
        %td= content.goals
        %td= link_to 'Show', content
        %td= link_to 'Edit', edit_content_path(content)
        %td= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Content', new_content_path

app/views/contents/new.html.haml
= render 'form'

app/views/contents/show.html.haml
-if @content.published? || current_user.permissions.to_i >= 30
  -if @show == true #requerimientos
    %nav{:id => "header", :class => "fixed w-full z-10 top-0"}
      %div{:id => "progress", :class => "h-1 z-20 top-0", :style => "background:linear-gradient(to right, green var(--scroll), transparent 0)"}
    %div{:class => "container w-full md:max-w-3xl mx-auto pt-20"}
      %div{:class => "w-full px-4 md:px-6 text-xl text-gray-800 leading-normal "}

        .text-base.md:text-sm.text-green-500.font-bold
          %p{:class =>"text-sm md:text-base font-normal text-gray-600"}
            =link_to @course.name, course_path(@course)
            >>
            =link_to @chapter.name, course_chapter_path(@course, @chapter)
          %h1{:class => "font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl"}
            = @content.name 
          
            
        -case @content.typeOfContent.to_i
          -when 1
            -# Texto enriquecido
            = @content.richContent
          -when 2
            -# Video
            .mx-auto.flex=raw(@content.embed)  
          -when 3
            -# Tweet
            =raw(@content.embed)
          -when 4
            -# Post de IG
            =raw(@content.embed)
          -when 5
            -# TikTok
            =raw(@content.embed)
          -else
            -# Contenido desconocido
            =raw(@content.embed)
        .my-4
        - boton = raw(inline_svg_tag "raise-hand.svg", class: 'h-8 w-8 inline-block animate-bounce') + "Contenido creado por los usuarios"
        .m-2.text-center{:class => "text-sm md:text-xl"}= link_to boton, content_user_contents_path(@content.id), :class => "m-2 bg-purple-200 shadow px-2 md:px-6 py-4 font-1 rounded-xl text-center hover:bg-purple-600 hover:text-white"
        =#.m-2.bg-purple-200.shadow.py-2.px-6.font-1.rounded-xl.text-center{:class => "hover:bg-purple-600 hover:text-white"}
        
          
          
        
        .my-8.mx-2.bg-gray-50.shadow.py-2.px-6.text-sm
          - case @content.priority.to_i
            -when 1
              %b Contenido prioritario y correlativo
              %p Necesario para adquirir los conocimientos básicos del curso y para avanzar al siguiente capítulo.
            -when 2
              %b Contenido prioritario
              %p Es necesario para adquirir los conocimientos básicos del curso, pero podrás avanzar de todos modos sin haberlo navegado por completo. 
            -when 3
              %b Contenido complementario
              %p Podrás saltar este contenido y aún así haber adquirido los conocimientos que se han considerado básicos para el curso. 
        
        .m-2.bg-gray-50.shadow.py-2.px-6.text-sm
          %b Después de este contenido deberías ser capaz de:
          %ul.list-disc
            -@content.goals.each do |e|
              %li
                = e
        -unless @content.minimumScore == nil
          .m-2.bg-gray-50.shadow.py-2.px-6.text-sm
            %p.font-bold Evaluación
            
            %p.text-center
              Puntos para superar el contenido: 
            
              %span.text-lg.text-green-800
                =@points.to_i
              de
              %span.text-xl.text-red-800=@content.minimumScore
            
            -# SI EL ESTUDIANTE YA APROBÓ EL CONTENIDO, NO DEBERÍAN IMPRIMIRSE LAS PRÓXIMAS DOS LÍNEAS
            -unless @points.to_i >= @content.minimumScore.to_i
              - boton = raw(inline_svg_tag "reading-book.svg", class: 'h-8 w-8 inline-block animate-bounce svgInverso') + "Ganarme esos puntos"
              .my-8.mx-2.text-center{:class => "text-sm md:text-xl"}= link_to boton, content_tests_path(@content.id), :class => "m-2 bg-green-200 shadow px-2 md:px-6 py-4 font-1 rounded-xl text-center hover:bg-green-600 hover:text-white"

          
        

        -# Siguiente contenido | Anterior
    %script
      var h = document.documentElement,
      b = document.body,
      st = 'scrollTop',
      sh = 'scrollHeight',
      progress = document.querySelector('#progress'),
      scroll;
      var scrollpos = window.scrollY;
      var header = document.getElementById("header");
      var navcontent = document.getElementById("nav-content");

      document.addEventListener('scroll', function() {

      /*Refresh scroll % width*/
      scroll = (h[st] || b[st]) / ((h[sh] || b[sh]) - h.clientHeight) * 100;
      progress.style.setProperty('--scroll', scroll + '%');

      /*Apply classes for slide in bar*/
      scrollpos = window.scrollY;

      if (scrollpos > 10) {
      header.classList.add("bg-white");
      header.classList.add("shadow");
      //navcontent.classList.remove("bg-gray-100");
      //navcontent.classList.add("bg-white");
      } else {
      //header.classList.remove("bg-white");
      header.classList.remove("shadow");
      //navcontent.classList.remove("bg-white");
      //navcontent.classList.add("bg-gray-100");

      }

      });
  -elsif @show == false
    %div{:class => "my-4 px-2 w-3/4 md:w-2/4 rounded-xl bg-purple-200 mx-auto text-center font-2"}
      .py-4.animate-pulse=inline_svg "padlock.svg", :class => "h-48 w-48 inline-block svgInverso"
      %p.py-2.text-2xl.font-bold No podés ver este contenido... 
      
      %p.py-4
        Necesitás
        %span.font-bold.text-purple-800.text-xl=@data[0][:puntos_requeridos]
        puntos en
        %span.font-bold.text-purple-800.animate-pulse=link_to @data[0][:requerimiento].name, content_path(@data[0][:requerimiento].id), :class => "hover: text-purple-400"
        y tenés
        %span.font-bold.text-purple-800.text-xl=@data[0][:puntos_obtenidos].to_i
-elsif @content.disabled?
  %div{:class => "my-4 px-2 w-3/4 md:w-2/4 rounded-xl bg-purple-200 mx-auto text-center font-2"}
    .py-4.animate-pulse=inline_svg "padlock.svg", :class => "h-48 w-48 inline-block svgInverso"
    %p.py-2.text-2xl.font-bold Contenido deshabilitado
    
    %p.py-4
      Todavía no habilitamos este contenido.