config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :leads
  get 'points/assign'
  get 'points/destroy'
  get 'points/consult'
  get 'points/view'
  resources :matriculations
  resources :contents do
    resources :user_contents do
      member do
        put 'like' => 'user_contents#like'
        get 'fijar' => 'user_contents#pinup'
        get 'banear' => 'user_contents#ban'
      end
    end
    resources :tests do
      post 'corregir' => 'tests#corregir'
    end
    post 'points' => 'points#consult'
    get 'publicar' => 'contents#publish'
    get 'deshabilitar' => 'contents#disable'
  end

  resources :courses do
    resources :chapters do
      get 'publicar' => 'chapters#publish'
    end
    get 'publicar' => 'courses#publish'
  end

  devise_for :users
  root 'home#index'
  get 'mycourses', to: 'courses#mycourses'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :course
  has_many :contents

  include AASM

  aasm do
    # Declaramos los estados
    state :in_draft, initial: true
    state :published

    # Declaramos los eventos
    event :publish do
      transitions from: :in_draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :in_draft
    end
  end
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :course
  belongs_to :chapter
  has_rich_text :richContent
  has_many :contents

  include AASM

  aasm do
    # Declaramos los estados
    state :in_draft, initial: true
    state :published, :disabled

    # Declaramos los eventos
    event :publish do
      transitions from: %i[in_draft disabled], to: :published
    end

    event :unpublish do
      transitions from: %i[published disabled], to: :in_draft
    end

    event :disable do
      transitions from: %i[published in_draft], to: :disabled
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :chapters
  has_many :contents, through: :chapters

  include AASM

  aasm do
    # States declarations
    state :in_draft, initial: true
    state :published

    # Events declarations
    event :publish do
      transitions from: :in_draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :in_draft
    end
  end
end

app/models/lead.rb
class Lead < ApplicationRecord
  validates :email, presence: true
  validates :name, presence: true
end

app/models/matriculation.rb
class Matriculation < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :content
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  acts_as_voter
  has_many :user_contents
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user_content.rb
class UserContent < ApplicationRecord
  belongs_to :user
  belongs_to :content

  acts_as_votable

  include AASM

  aasm do
    # Declaramos los estados

    state :published, initial: true
    state :featured, :banned

    # Declaramos los eventos
    # GET banear
    event :ban do
      transitions from: %i[published featured], to: :banned
    end
    # GET publicar
    event :publish do
      transitions from: :banned, to: :published
    end
    # GET fijar
    event :pinup do
      transitions from: :published, to: :featured
    end
    # GET fijar
    event :unpinup do
      transitions from: :featured, to: :published
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @courses = Course.all
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: %i[show edit update destroy]

  before_action :authenticate_user!, only: %i[show index edit update destroy]
  before_action :check_god, only: %i[show index edit update destroy]

  # GET /leads or /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1 or /leads/1.json
  def show; end

  # GET /leads/new
  def new
    @lead = Lead.new
    courses = Course.select(:id, :name).all

    @courses = []
    courses.each do |c|
      @courses.push([c.name, c.id])
    end
  end

  # GET /leads/1/edit
  def edit; end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)

    @lead.user = current_user if user_signed_in?
    @lead.status = 0
    respond_to do |format|
      if @lead.save
        format.html { redirect_to root_path, notice: 'En breve nos vamos a comunicar con vos :-)' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lead_params
    params.require(:lead).permit(:user, :status, :course, :name, :email, :info)
  end

  def check_god
    if current_user.permissions.nil?
      redirect_to root_path, notice: 'Pfff... Tomate el palo...'
    else
      redirect_to root_path, notice: 'Naaa. Estás re loco vo, amigo.' unless current_user.permissions >= 50
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/leads/_form.html.haml
-if user_signed_in?
  -unless current_user.name == nil
    - nombre = current_user.name
  -else
    - nombre = ""
  -unless current_user.email == nil
    - email = current_user.email
  -else
    - email = ""

= form_for @lead do |f|
  - if @lead.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lead.errors.count, "error")} prohibited this lead from being saved:"
      %ul
        - @lead.errors.full_messages.each do |message|
          %li= message

  .field.font-2.py-2
    ¿En qué estás interesado?
    =# f.text_field :course, :value => params[:course], :class => "textBox"
    = f.select :course, options_for_select(@courses,params[:course]), {}, :class => "rounded relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 bg-white text-lg font-1"
  .field.font-2.py-2
    Tu nombre
    = f.text_field :name, :value => nombre, :class => "textBox"
  .field.font-2.py-2
    Tu email
    = f.text_field :email, :value => email, :class => "textBox"
  .field.font-2.py-2
    ¿Querés decirnos algo? (opcional)
    = f.text_area :info, :class => "textBox"
  .text-center.py-4
    = f.submit 'Enviar', :class => "botonLargo"

app/views/leads/edit.html.haml
%h1 Editing lead

= render 'form'

= link_to 'Show', @lead
\|
= link_to 'Back', leads_path

app/views/leads/index.html.haml
%h1 Listing leads

%table
  %thead
    %tr
      %th User
      %th Status
      %th Course
      %th Name
      %th Email
      %th Info
      %th
      %th
      %th

  %tbody
    - @leads.each do |lead|
      %tr
        %td= lead.user
        %td= lead.status
        %td= lead.course
        %td= lead.name
        %td= lead.email
        %td= lead.info
        %td= link_to 'Show', lead
        %td= link_to 'Edit', edit_lead_path(lead)
        %td= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lead', new_lead_path

app/views/leads/new.html.haml
.min-h-screen.flex.items-center.justify-center.py-12.px-4{class: "sm:px-6 sm:bg-purple-600 lg:px-8"}
  .max-w-md.w-full.space-y-8.bg-white.p-8.rounded-xl{class: "sm:shadow"}
    %div
      %h2.loginTitle.py-4 Pedir info
      = render 'form'
      
    =# f.label :email, :class => "sr-only"
    
    =# f.email_field :email, autofocus: true, autocomplete: "email", :class => 'textBox', placeholder: "E-mail"

app/views/leads/show.html.haml
%p#notice= notice

%p
  %b User:
  = @lead.user
%p
  %b Status:
  = @lead.status
%p
  %b Course:
  = @lead.course
%p
  %b Name:
  = @lead.name
%p
  %b Email:
  = @lead.email
%p
  %b Info:
  = @lead.info

= link_to 'Edit', edit_lead_path(@lead)
\|
= link_to 'Back', leads_path