config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :leads
  get 'points/assign'
  get 'points/destroy'
  get 'points/consult'
  get 'points/view'
  resources :matriculations
  resources :contents do
    resources :user_contents do
      member do
        put 'like' => 'user_contents#like'
        get 'fijar' => 'user_contents#pinup'
        get 'banear' => 'user_contents#ban'
      end
    end
    resources :tests do
      post 'corregir' => 'tests#corregir'
    end
    post 'points' => 'points#consult'
    get 'publicar' => 'contents#publish'
    get 'deshabilitar' => 'contents#disable'
  end

  resources :courses do
    resources :chapters do
      get 'publicar' => 'chapters#publish'
    end
    get 'publicar' => 'courses#publish'
  end

  devise_for :users
  root 'home#index'
  get 'mycourses', to: 'courses#mycourses'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_content.rb
class UserContent < ApplicationRecord
  belongs_to :user
  belongs_to :content

  acts_as_votable

  include AASM

  aasm do
    # Declaramos los estados

    state :published, initial: true
    state :featured, :banned

    # Declaramos los eventos
    # GET banear
    event :ban do
      transitions from: %i[published featured], to: :banned
    end
    # GET publicar
    event :publish do
      transitions from: :banned, to: :published
    end
    # GET fijar
    event :pinup do
      transitions from: :published, to: :featured
    end
    # GET fijar
    event :unpinup do
      transitions from: :featured, to: :published
    end
  end
end

app/controllers/user_contents_controller.rb
class UserContentsController < ApplicationController
  before_action :set_user_content, only: %i[show edit update destroy ban pinup]
  before_action :set_content
  before_action :authenticate_user!
  before_action :check_owner, only: %i[edit update destroy]
  before_action :check_permissions, only: %i[ban pinup]

  respond_to :js, :html, :json

  # GET /user_contents or /user_contents.json
  def index
    @user_contents = UserContent.where(content_id: @content).order(created_at: :desc)
  end

  # GET /user_contents/1 or /user_contents/1.json
  def show; end

  # GET /user_contents/1/banear
  def ban
    # Sólo pueden BANEAR los tutores
    if @permissions >= 20

      # Si está baneado lo publicamos
      if @user_content.banned?
        @user_content.publish!
        redirect_to content_user_contents_path(@content), notice: 'Publicamos el contenido.'
      # Si está publicado (o fijado) lo baneamos
      else
        @user_content.ban!
        redirect_to content_user_contents_path(@content), notice: 'Censuramos el contenido.'
      end
    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto'
    end
  end

  # GET /user_contents/1/fijar
  def pinup
    # Sólo pueden FIJAR los tutores
    if @permissions >= 20

      # Si está baneado lo publicamos
      if @user_content.published?
        @user_content.pinup!
        redirect_to content_user_contents_path(@content), notice: 'Fijamos el contenido como destacado.'
      # Si está publicado (o fijado) lo baneamos
      elsif @user_content.featured?
        @user_content.unpinup!
        redirect_to content_user_contents_path(@content), notice: 'Dejamos de destacar este contenido.'
      # Si no probablemente esté baneado.
      else
        redirect_to content_user_contents_path(@content),
                    notice: 'No pudimos fijar el contenido. Verificá que no esté baneado.'
      end

    else
      # Redirigir
      redirect_to root_path, notice: 'No tenés permiso para esto'
    end
  end

  # GET /user_contents/new
  def new
    @user_content = UserContent.new
  end

  # GET /user_contents/1/edit
  def edit; end

  # POST /user_contents or /user_contents.json
  def create
    @user_content = UserContent.new(user_content_params)
    @user_content.user_id = current_user.id
    @user_content.content_id = @content.id

    respond_to do |format|
      if @user_content.save
        format.html do
          redirect_to content_user_contents_path, notice: '¡Bien ahí! Acabás de crear un contenido, crack.'
        end
        format.json { render :show, status: :created, location: @user_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_contents/1 or /user_contents/1.json
  def update
    respond_to do |format|
      if @user_content.update(user_content_params)
        format.html do
          redirect_to content_user_contents_path, notice: 'Ya cambiamos el contenido, tal como lo pediste.'
        end
        format.json { render :show, status: :ok, location: @user_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_contents/1 or /user_contents/1.json
  def destroy
    @user_content.destroy
    respond_to do |format|
      format.html { redirect_to content_user_contents_path, notice: 'Ya borramos el contenido.' }
      format.json { head :no_content }
    end
  end

  def like
    @user_content = UserContent.find(params[:id])
    if params[:format] == 'like'
      @user_content.liked_by current_user
    elsif params[:format] == 'unlike'
      @user_content.unliked_by current_user
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_content
    @user_content = UserContent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_content_params
    params.require(:user_content).permit(:markdownContent, :content_type, :sticked, :claps, :responseTo, :user_id,
                                         :content_id)
  end

  def set_content
    @content = Content.find(params[:content_id])
  end

  def check_owner
    redirect_to root_path, notice: 'No estás autorizado a hacer eso.' unless @user_content.user == current_user
  end

  def check_permissions
    matricula = Matriculation.find_by(user: current_user, course: @content.course)

    @permissions = if matricula.nil?
                     0
                   else
                     matricula.permissions
                   end
  end
end

app/helpers/user_contents_helper.rb
module UserContentsHelper
end

app/views/user_contents/_form.html.haml
= form_for [@content,@user_content] do |f|
  .bg-gray-200.p-4.h-screen
    .bg-white.rounded-xl.m-6.p-6.md:container.mx-auto
      %p.m-2
        - flecha= inline_svg_tag "arrow.svg", class: 'h-8 inline-block svgVioleta'
        = link_to flecha, :back
      -if current_user.avatar.attached?        
        =image_tag current_user.avatar, :class => "float-left w-12 h-12 rounded-full m-2"
      -else
        =image_tag "extraterrestre.svg", :class=> "float-left w-12 h-12 rounded-full m-2"
        
      =f.text_area :markdownContent, :class => "p-4 w-full h-40 text-2xl font-2 resize-y lg:h-80 md:w-5/6", :placeholder => "¿Cuál es tu aporte?"

      .inline-grid.grid-cols-2.gap-x-4
        %span
          = f.select :content_type, options_for_select([['Duda (será respondida)', 1], ['Aporte', 2]]), {}, :class => "rounded relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 bg-white text-lg font-1"
        %span
          =# Este label va sólo si el usuario tiene permisos de edición en el curso
          %label.text-lg.font-1
            = f.check_box :sticked
            Fijado 
      .text-right
        =f.submit 'Publicar', :class => 'botonVerde'
        



    - if @user_content.errors.any?
      #error_explanation
        %h2= "#{pluralize(@user_content.errors.count, "error")} prohibited this user_content from being saved:"
        %ul
          - @user_content.errors.full_messages.each do |message|
            %li= message

app/views/user_contents/edit.html.haml
= render 'form'

=# link_to 'Show', @user_content

app/views/user_contents/index.html.haml
.bg-gray-200.min-h-screen.overflow-hidden
  .container.mx-auto.py-4
    .mx-4.text-center
     
      - flecha= inline_svg_tag "arrow.svg", class: 'h-8 inline-block svgVioleta'
      .float-left= link_to flecha, content_path(@content)
      = link_to 'Crear contenido', new_content_user_content_path(@content), :class => "botonVerde"
    .py-6.font-2
      - if @user_contents.length == 0
        .text-2xl ¡Epa! Parece que todavía nadie se animó a colaborar.
        .text-3xl= link_to 'Sé el primero.', new_content_user_content_path(@content)
      -else
        -#Cantidad de aportes de la comunidad:
        =#@user_contents.length

    - @user_contents.each do |user_content|
      -unless user_content.banned?
        .bg-white.m-2.p-4.rounded-xl
          - if user_content.responseTo?
            En respuesta a 
            = user_content.responseTo
          -if user_content.user.avatar.attached?        
            = image_tag user_content.user.avatar, :class => "bg-white img w-8 h-8 rounded-full inline-block mx-2"
          -else
            =image_tag "extraterrestre.svg", :class=> "bg-white img w-8 h-8 rounded-full inline-block mx-2"
          -case user_content.content_type
            -when 1
              Duda de
            -when 2
              Aporte de 
            -else
              Algo que dijo

          -unless user_content.user.name == nil
            = user_content.user.name
          -else
            = user_content.user.email
          -markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
          .md= raw(markdown.render(user_content.markdownContent))
        
          .grid.grid-cols-3
            %div
              %span=# inline_svg_tag "clap.svg", class: 'w-8 h-8 inline-block svgVioleta' 
              
              %span.font-1= user_content.get_likes.size
              -if current_user.liked? user_content
                -dislike = inline_svg_tag "clap.svg", class: 'w-8 h-8 inline-block svgInverso'
                =link_to dislike, like_content_user_content_path(@content, user_content, 'unlike'), method: :put 
              -else
                -like = inline_svg_tag "clap.svg", class: 'w-8 h-8 inline-block svgVioleta'
                =link_to like, like_content_user_content_path(@content, user_content, 'like'), method: :put 

            -if current_user == user_content.user
              %div.text-center= link_to 'Editar', edit_content_user_content_path(@content,user_content), :class => "botonVerde"
              %div.text-right= link_to 'Borrar', [@content,user_content], method: :delete, data: { confirm: '¿Estás seguro que querés borrar esto?' }, :class => "botonRojo"

          - if user_content.featured?
            .sticked CONTENIDO FIJADO
          -if current_user.permissions.to_i >= 20
            .sticked ID del contenido: #{user_content.id}
            .sticked Tus permisos: #{current_user.permissions.to_i}


            =# link_to 'Show', content_user_content_path(@content, user_content)
      -else
        -if current_user.permissions.to_i >= 20
          .bg-red-600.m-2.p-4.rounded-xl
            - if user_content.responseTo?
              En respuesta a 
              = user_content.responseTo
            -if user_content.user.avatar.attached?        
              = image_tag user_content.user.avatar, :class => "bg-white img w-8 h-8 rounded-full inline-block mx-2"
            -else
              =image_tag "extraterrestre.svg", :class=> "bg-white img w-8 h-8 rounded-full inline-block mx-2"
            -case user_content.content_type
              -when 1
                Duda de
              -when 2
                Aporte de 
              -else
                Algo que dijo

            -unless user_content.user.name == nil
              = user_content.user.name
            -else
              = user_content.user.email
            -markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
            .md= raw(markdown.render(user_content.markdownContent))
          
            .grid.grid-cols-3
              %div
                %span=# inline_svg_tag "clap.svg", class: 'w-8 h-8 inline-block svgVioleta' 
                
                %span.font-1= user_content.get_likes.size
                -if current_user.liked? user_content
                  -dislike = inline_svg_tag "clap.svg", class: 'w-8 h-8 inline-block svgInverso'
                  =link_to dislike, like_content_user_content_path(@content, user_content, 'unlike'), method: :put 
                -else
                  -like = inline_svg_tag "clap.svg", class: 'w-8 h-8 inline-block svgVioleta'
                  =link_to like, like_content_user_content_path(@content, user_content, 'like'), method: :put 

              -if current_user == user_content.user
                %div.text-center= link_to 'Editar', edit_content_user_content_path(@content,user_content), :class => "botonVerde"
                %div.text-right= link_to 'Borrar', [@content,user_content], method: :delete, data: { confirm: '¿Estás seguro que querés borrar esto?' }, :class => "botonRojo"

            - if user_content.featured?
              .sticked CONTENIDO FIJADO
            .sticked ID del contenido: #{user_content.id}
            .sticked Tus permisos: #{current_user.permissions.to_i}

app/views/user_contents/new.html.haml
= render 'form'

app/views/user_contents/show.html.haml
%p#notice= notice

%p
  %b Markdowncontent:
-markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
.md= raw(markdown.render(@user_content.markdownContent))
%p
  %b Type:
  = @user_content.content_type
%p
  %b Sticked:
  = @user_content.sticked
%p
  %b Claps:
  = @user_content.claps
%p
  %b Responseto:
  = @user_content.responseTo
%p
  %b User:
  = @user_content.user
%p
  %b Content:
  = @user_content.content

-unless current_user.permissions == nil
  -if current_user.permissions >= 50
  = link_to 'Edit', edit_content_user_content_path(@content,@user_content)
\|
= link_to 'Back', content_user_contents_path